#主从数据库配置
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:                        #主数据库
        url: jdbc:mysql://127.0.0.1:3306/myblogs?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 111111
        initial-size: 5
        min-idle: 1
        max-active: 100
        max-wait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnReturn: false  
        testOnBorrow: false
        testWhileIdle: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20      
    slave:                          #从数据库
        url: jdbc:mysql://127.0.0.1:3306/myblogs-test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 111111
        initial-size: 5
        min-idle: 1
        max-active: 100
        max-Wait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnReturn: false  
        testOnBorrow: false
        testWhileIdle: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
 

Spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      
